platform :ios, '11.0'

target 'COOL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleSignIn'
  pod 'Firebase/Auth'

  target 'COOLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'COOLUITests' do
    # Pods for testing
  end

end
